import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torch.utils.data import DataLoader
import os

# Import the classes we just built in the other files
from dataset import NameDataset
from models import VanillaRNN, CharBLSTM, AttentionRNN

# Ensure reproducibility
torch.manual_seed(42)

def train_model(model_name, model, dataloader, dataset, epochs=15, lr=0.005):
    """Trains the given model and calculates the loss."""
    print(f"\n" + "="*40)
    print(f" TRAINING: {model_name}")
    print("="*40)
    
    # We ignore the <PAD> token in our loss calculation so the model 
    # doesn't cheat by just learning to predict empty spaces at the end of short names!
    criterion = nn.CrossEntropyLoss(ignore_index=dataset.char2idx['<PAD>'])
    optimizer = optim.Adam(model.parameters(), lr=lr)
    
    model.train()
    for epoch in range(epochs):
        total_loss = 0
        for x, y in dataloader:
            optimizer.zero_grad()
            
            # Forward pass
            logits, _ = model(x)
            
            # CrossEntropyLoss expects shapes: (batch_size * seq_len, vocab_size) and (batch_size * seq_len)
            loss = criterion(logits.reshape(-1, logits.size(2)), y.reshape(-1))
            
            # Backward pass and optimize
            loss.backward()
            optimizer.step()
            total_loss += loss.item()
            
        if (epoch + 1) % 3 == 0 or epoch == 0:
            print(f"  Epoch {epoch+1}/{epochs} | Loss: {total_loss/len(dataloader):.4f}")
            
    return model

def generate_names(model_name, model, dataset, num_names=5, max_len=15, temperature=0.8):
    """Generates completely new names character by character."""
    print(f"\n--- Names Generated by {model_name} ---")
    model.eval()
    generated_names = []
    
    with torch.no_grad():
        for _ in range(num_names):
            # Start the sequence with the <SOS> (Start of Sequence) token
            input_seq = [dataset.char2idx['<SOS>']]
            name = ""
            
            for _ in range(max_len):
                x = torch.tensor([input_seq], dtype=torch.long) # Shape: (1, current_seq_len)
                
                logits, _ = model(x)
                
                # Get the predictions for the VERY LAST character in our growing sequence
                next_char_logits = logits[0, -1, :] 
                
                # Apply temperature to scale the probabilities
                next_char_probs = F.softmax(next_char_logits / temperature, dim=0)
                
                # Sample the next character from the probability distribution
                next_char_idx = torch.multinomial(next_char_probs, 1).item()
                
                # Stop if the model predicts the <EOS> (End of Sequence) token
                if next_char_idx == dataset.char2idx['<EOS>']:
                    break
                    
                name += dataset.idx2char[next_char_idx]
                input_seq.append(next_char_idx)
                
            generated_names.append(name.capitalize())
            print(f"  -> {name.capitalize()}")
            
    return generated_names

def main():
    # Setup paths dynamically
    current_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.abspath(os.path.join(current_dir, "..", ".."))
    
    # Path to the 1000 names you generated with the LLM
    data_path = os.path.join(project_root, "data", "processed", "Training_Names.txt")
    
    if not os.path.exists(data_path):
        print(f"ERROR: Could not find your Training_Names.txt at {data_path}")
        print("Please make sure you saved your 1000 generated names there!")
        return

    # Hyperparameters
    BATCH_SIZE = 64
    EMBED_SIZE = 32
    HIDDEN_SIZE = 64
    EPOCHS = 15
    LR = 0.005

    # 1. Load Dataset
    dataset = NameDataset(data_path)
    dataloader = DataLoader(dataset, batch_size=BATCH_SIZE, shuffle=True)
    vocab_size = dataset.vocab_size

    # 2. Initialize Models
    vanilla_rnn = VanillaRNN(vocab_size, EMBED_SIZE, HIDDEN_SIZE)
    blstm_rnn = CharBLSTM(vocab_size, EMBED_SIZE, HIDDEN_SIZE)
    attn_rnn = AttentionRNN(vocab_size, EMBED_SIZE, HIDDEN_SIZE)

    # 3. Train & Generate (Vanilla RNN)
    vanilla_rnn = train_model("Vanilla RNN", vanilla_rnn, dataloader, dataset, EPOCHS, LR)
    generate_names("Vanilla RNN", vanilla_rnn, dataset)

    # 4. Train & Generate (BLSTM)
    blstm_rnn = train_model("Bidirectional LSTM", blstm_rnn, dataloader, dataset, EPOCHS, LR)
    generate_names("Bidirectional LSTM", blstm_rnn, dataset)

    # 5. Train & Generate (Attention RNN)
    attn_rnn = train_model("Attention RNN", attn_rnn, dataloader, dataset, EPOCHS, LR)
    generate_names("Attention RNN", attn_rnn, dataset)
    
    print("\nSUCCESS: Problem 2 Training and Generation is complete!")

if __name__ == "__main__":
    main()
